version: '3.8'

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    expose:
      - '9000'
    volumes:
      - "./:/var/www/html/app"
      - "/var/www/html/app/var"
      - "/var/www/html/app/vendor"
    working_dir: /var/www/html/app
